### ISSUE TITLE
TMC9660-3PH-EVAL Board with Landungsbrücke V2

### ISSUE THREAD

**Issue by marlesus** [analogdevicesinc/TMC-EvalSystem#11]
Hello,

It seems that the TMC9660-3PH-EVAL board does not work with the Landungsbrücke V2. 
Is this a known issue ?
The eval board is recognized in TMCL-IDE, I start the Ubl Bootstrapping procedure, IC is recognized, but the Axis and other evaluation tools are not shown at all in the tree veiw on the left side of TMCL-IDE.
The same works without problems with Landungsbrücke **V3**, but **not** with the **V2**...

I have followed your instructions very carefully:
1. TMCL-IDE v4.5 with Landungsbrücke FW v3.10.6
2. TMCL-IDE v4.6 with Landungsbrücke FW v3.10.9 (latest available at the moment), and v3.10.8.

No use.
It just does not work with the Landungsbrücke V2.

Any ideas, suggestions ?

Best regards,
Paul

**Comment by marlesus** [comment]
Can anyone please help me with the issue above ? It's really urgent, and it is nowhere documented that the Landungsbrücke V2.0 does not work with the TMC9660-3PH-EVAL board... :(

**Comment by trinamic-ASU** [comment]
Hi, 
Many apologies for the delayed response.
This issue has been fixed! Please use the latest FW released version 3.10.10.

We appreciate your feedback.

**Comment by marlesus** [comment]
Hi trinamic-ASU,

The TMC9660-3PH-EVAL board recognition works, but with using the Landungsbrücke V2, I still get the error that you can see in the attached picture... :(
I cannot go over this step, so something is still not working fine with the firmware for the Landungsbrücke V2.

Can you please tell me what could be the problem, or help me in this direction?

Best regards,
Paul

![Image](https://github.com/user-attachments/assets/8153f7f9-aaa1-4cc7-820a-b55351d37f44)

**Comment by trinamic-ASU** [comment]
Hi Paul,
Can you please share TMCL log?

**Comment by marlesus** [comment]
Hi,
You have the log here.

Thank you,
Paul

[TMCLlog.txt](https://github.com/user-attachments/files/19390900/TMCLlog.txt)

**Comment by trinamic-jh** [comment]
Hey @marlesus I was able to reproduce the issue. The root course is a timing issue in the TMCL-IDE. 
With TMC9660 the command/sec throuput is siginficantly lower with LBV2 that with LBV3. 
For this reason, I would recommend using Landungsbruecke V3. The issue will be addressed in a future IDE release.
